### ISSUE TITLE
Unrecoverable Exception when WeeWx attempts to load the driver.   missing parentheses in call to print Syslog attached.

### ISSUE THREAD

**Issue by mytechguyri** [David-Enst/WeeWX-BCRobotics#4]
Feb  5 23:25:55 direwolf weewx[739] INFO weewx.engine: Loading station type BCRobotics (user.BCRobotics)
Feb  5 23:25:55 direwolf weewx[739] CRITICAL __main__: Caught unrecoverable exception:
Feb  5 23:25:55 direwolf weewx[739] CRITICAL __main__:     ****  Missing parentheses in call to 'print'. Did you mean print("%s\r" % msg)? (BCRobotics.py, line 118)
Feb  5 23:25:55 direwolf weewx[739] CRITICAL __main__:     ****  Traceback (most recent call last):
Feb  5 23:25:55 direwolf weewx[739] CRITICAL __main__:     ****    File "/usr/share/weewx/weewxd", line 147, in main
Feb  5 23:25:55 direwolf weewx[739] CRITICAL __main__:     ****      engine = weewx.engine.StdEngine(config_dict)
Feb  5 23:25:55 direwolf weewx[739] CRITICAL __main__:     ****    File "/usr/share/weewx/weewx/engine.py", line 81, in __init__
Feb  5 23:25:55 direwolf weewx[739] CRITICAL __main__:     ****      self.setupStation(config_dict)
Feb  5 23:25:55 direwolf weewx[739] CRITICAL __main__:     ****    File "/usr/share/weewx/weewx/engine.py", line 108, in setupStation
Feb  5 23:25:55 direwolf weewx[739] CRITICAL __main__:     ****      __import__(driver)
Feb  5 23:25:55 direwolf weewx[739] CRITICAL __main__:     ****    File "/usr/share/weewx/user/BCRobotics.py", line 118
Feb  5 23:25:55 direwolf weewx[739] CRITICAL __main__:     ****      print "%s\r" % msg
Feb  5 23:25:55 direwolf weewx[739] CRITICAL __main__:     ****            ^
Feb  5 23:25:55 direwolf weewx[739] CRITICAL __main__:     ****  SyntaxError: Missing parentheses in call to 'print'. Did you mean print("%s\r" % msg)?
Feb  5 23:25:55 direwolf weewx[739] CRITICAL __main__:     ****  Exiting.

**Comment by David-Enst** [comment]
New driver just uploaded. Never saw that error before!?
